//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerformanceAppraisalProj.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionHistory
    {
        public long RowID { get; set; }
        public string EmployeeID { get; set; }
        public string AppraisalDocNo { get; set; }
        public string Status { get; set; }
        public string Action { get; set; }
        public string Comments { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> AppraisalYear { get; set; }
        public string Responsibility { get; set; }
    }
}
