//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerformanceAppraisalProj.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppraisalDocHeader
    {
        public long RowID { get; set; }
        public string AppraisalDocNo { get; set; }
        public Nullable<int> AppraisalYear { get; set; }
        public Nullable<System.DateTime> AppraisalPeriodFrom { get; set; }
        public Nullable<System.DateTime> AppraisalPeriodTo { get; set; }
        public Nullable<System.DateTime> AppraisalDate { get; set; }
        public string EmployeeName { get; set; }
        public string Position { get; set; }
        public string DepartmentName { get; set; }
        public string CompanyID { get; set; }
        public string EmployeeStrength { get; set; }
        public string EmployeeImprovement { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string AppraisalStatus { get; set; }
        public string AppraisalGrade { get; set; }
        public Nullable<decimal> AppraisalTotalScore { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string EmployeeID { get; set; }
    }
}
