//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerformanceAppraisalProj.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppraisalStatusMaster
    {
        public long RowID { get; set; }
        public string AppraisalStatus { get; set; }
        public Nullable<int> AppraisalStatusID { get; set; }
    }
}
