//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerformanceAppraisalProj.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppraisalDocLine
    {
        public long RowID { get; set; }
        public string AppraisalDocNo { get; set; }
        public Nullable<int> AppraisalDocLineNo { get; set; }
        public Nullable<int> QuestionLineNo { get; set; }
        public string QuestionDesc { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<decimal> CalculatedScore { get; set; }
        public Nullable<decimal> QuestionWeight { get; set; }
        public string Remark { get; set; }
        public Nullable<int> QuestionType { get; set; }
    }
}
