//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerformanceAppraisalProj.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PerformanceAppraisalEntities : DbContext
    {
        public PerformanceAppraisalEntities()
            : base("name=PerformanceAppraisalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppraisalDocHeader> AppraisalDocHeaders { get; set; }
        public virtual DbSet<AppraisalDocLine> AppraisalDocLines { get; set; }
        public virtual DbSet<AppraisalGradeMaster> AppraisalGradeMasters { get; set; }
        public virtual DbSet<AppraisalStatusMaster> AppraisalStatusMasters { get; set; }
        public virtual DbSet<AppraisalTemplate> AppraisalTemplates { get; set; }
        public virtual DbSet<ApprovalHistory> ApprovalHistories { get; set; }
        public virtual DbSet<DepartmentMaster> DepartmentMasters { get; set; }
        public virtual DbSet<EmployeeGroupMaster> EmployeeGroupMasters { get; set; }
        public virtual DbSet<EmployeeMaster> EmployeeMasters { get; set; }
        public virtual DbSet<EmployeeSubGroupMaster> EmployeeSubGroupMasters { get; set; }
        public virtual DbSet<QuestionTypeMaster> QuestionTypeMasters { get; set; }
        public virtual DbSet<ScoreMaster> ScoreMasters { get; set; }
        public virtual DbSet<CompanyMaster> CompanyMasters { get; set; }
        public virtual DbSet<ActionHistory> ActionHistories { get; set; }
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<HREmployee> HREmployees { get; set; }
    
        public virtual ObjectResult<spListAppraisalCompleteTask_Result> spListAppraisalCompleteTask(string domainName)
        {
            var domainNameParameter = domainName != null ?
                new ObjectParameter("DomainName", domainName) :
                new ObjectParameter("DomainName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spListAppraisalCompleteTask_Result>("spListAppraisalCompleteTask", domainNameParameter);
        }
    }
}
