//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerformanceAppraisalProj.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionTypeMaster
    {
        public long RowID { get; set; }
        public Nullable<int> QuestionType { get; set; }
        public string QuestionTypeDesc { get; set; }
        public string QuestionTypeDesc2 { get; set; }
    }
}
